FROM wordpress:cli-php{{ env.phpVersion }} AS wp-cli

FROM inrage/docker-php:{{ env.phpVersion }}

# install WP-CLI
COPY --from=wp-cli /usr/local/bin/wp /usr/local/bin/wp

COPY --chown=inr wp-config-docker.php /usr/src/wordpress/
COPY bin /usr/local/bin

USER root

{{ if env.variant == "apache-redis" then ( -}}
RUN set -eux; \
    pecl install redis; \
    docker-php-ext-enable redis;
{{ ) else "" end -}}

COPY crontab /etc/crontab
RUN chmod 0644 /etc/crontab

USER inr
