FROM wordpress:cli-php{{ env.phpVersion }} AS wp-cli

FROM inrage/docker-php:{{ env.phpVersion }}

# install WP-CLI
COPY --from=wp-cli /usr/local/bin/wp /usr/local/bin/wp


USER root

{{ if env.variant == "apache-redis" then ( -}}
RUN set -eux; \
    pecl install redis; \
    docker-php-ext-enable redis;
{{ ) else "" end -}}

USER inr

COPY templates /etc/gotpl/
COPY bin /usr/local/bin

COPY init /docker-entrypoint-init.d/
